name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Fetch JOSM jar
      run: |
        mkdir -p lib
        curl -L -o lib/josm.jar https://josm.openstreetmap.de/josm-tested.jar
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
